### ISSUE TITLE
render responsive svgs by default

### ISSUE THREAD

**Issue by rjmoggach** [PEM--/fview-svg#4]
I thought this would take care of making svgs responsive inside their surface but simply setting the surface size isn't enough. It's especially noticeable if you start with Y rotated surfaces.

i've used the following method before:

[SVG into liquid layout
or Responsive Web Design](http://soqr.fr/testsvg/embed-svg-liquid-layout-responsive-web-design.php)

Will confirm if that works - maybe something to include?

**Comment by PEM--** [comment]
Check my README: https://github.com/PEM--/fview-svg#preparing-your-assets

That's exactly what I advise to do :wink:

**Comment by rjmoggach** [comment]
yeah - did that. that's not the issue.

only way I could get SVGs to be responsive was wrapping them in a div.

[mogfam.meteor.com](http://mogfam.meteor.com)

[https://github.com/robmoggach/famous-views-testing](https://github.com/robmoggach/famous-views-testing)

...going to use a Surface for now and do this manually.

Can you reopen this issue?

**Comment by PEM--** [comment]
Indeed, you've used a `ContainerSurface`.

**Comment by rjmoggach** [comment]
Is there a substantive and documented reason for not doing that? Please elaborate...

**Comment by PEM--** [comment]
A `ContainerSurface` creates its own context. Therefore, it doesn't constrain its childs. This is why you've added a `div`. A `Modifier` or a `StateModifier` would be more appropriate.

If you do something like, you should be good to go:

``` jade
+ContainerSurface ...
  +StateModifier ...
    +FviewSvg ...
```
